DROP TABLE IF EXISTS artworks;
DROP TABLE IF EXISTS artists;

CREATE TABLE artists
(
id SERIAL8 PRIMARY KEY,
name VARCHAR(255),
style VARCHAR(255),
image VARCHAR(255),
bio TEXT
);

CREATE TABLE artworks
(
id SERIAL8 PRIMARY KEY,
title VARCHAR(255),
year INT2,
category VARCHAR(255),
image VARCHAR(255),
artist_id INT4 REFERENCES artists(id) ON DELETE CASCADE
);
